#+TITLE: Presupuestos y costos
#+AUTHOR: Juan David Rodas Barco
#+DESCRIPTION: Haciendo la descripción de los costos para una simple UI
#+DATE: <2023-03-14 Tue>

* Ingeniería del software

Buscando presupuestos, costos y tiempos en la ejecución un proyecto de software

** Proyecto

Se quiere tener un sistema en el cual se necesite hacer el pago de la nomina de una empresa, este software se encargara de generar el recibo de pago con toda la información necesaria para su ejecucion.

Este debe cumplir con los siguientes requerimientos:

1) Frontend and Backend, cuanto cuesta en terminos de tiempo y dinero
2) Generar el costo de la implementación
3) Generar el recibo de pago con toda la información
4) Mostrar el valor de la nomina
5) Tiempo de implementación

*** Frontend and backend, cuanto cuesta

La hora de un desarrollador fullstack en colombia es de *5 dolares*, lo que se convertirian en 30 dolares semanales, que al mes seriàn *927 dolares*.

**** Nomina

Empecemos por el concepto de nomina, este concepto es la forma de como representar la liquidaciòn y el pago de los salarios, reflejando las remuneraciones que le corresponden.

#+begin_quote
No contaremos con disposiciones legales como retenciones y seguridad para el calculo
#+end_quote

***** Como se hace una nomina

De debe tener los siguientes aspectos

1) Còdigo de cuenta
2) Domicilio
3) Empresa, razòn social
4) Grupo de cotizaciòn
5) Grupo profesional
6) Nit
7) Nit Trabajador
8) Nùmero seguridad social
9) Trabajor - su nombre

***** Devengos de la nòmina

1) Salario base
2) Complemento salarial
3) Retribuciòn por horas extras
4) Retribuciòn por horas complementarias
5) Pagas extraordinarias
6) Salario en especie
   
   
**** Cuanto tiempo cuesta implementar el proyecto

Tener en cosideraciòn lo siguiente

- Arquitectura del sistema
- Base de datos
- Plataforma de desarrollo para el backend
- Plataforma de desarrollo para el frontend
- Total de nùmero de empleados
- Total nùmero de desarrolladores e ingenieros a contratar

***** Arquitectura del sistema

Al ser solo un generador de nomina para una cantidad de n empleados se necesitarà calcular el *salario* de manera eficiente, aparte de eso se debe calcular los devengos de la nòmina.

***** Bases de datos

Las soluciones que ofrecen en cuanto a bases de datos son sufìcientes para almacenar los datos, desde bases de datos relacionales, _que serìa lo màs optimo_, hasta las no relacionales...

***** Platafoma para el desarrollo backend

Python, rust y otros lenguajes de programaciòn brindan alternativas para el desarrollo backend por lo que no nos preocuparemos por cual lenguage es el màs propicio parà el trabajo...

***** Plataforma para el desarrollo frontend

Pues desde html, js, css, pasando por frameworks como react, angular, vue, stelve entre otros como flask, django, yew, rocket; No tendremos en cuenta la plataforma por ahora

***** Total de nùmero de ingenieros y desarrolladores a contratar

El proyecto es de pequeña embergadura para una microempresa entonces siguiendo el orden de ideas estarìa compuesto por lo sigiente:

1) Ingeniero de software 1
2) Grupo de desarrolladores fullstack 2
   

**** Balance preliminar

| Nùmero de personas | Cargo                   | Valor de Hora |
|                  2 | Desarrollador Fullstack |             8 |
|                  1 | Ingeniero de software   |            10 |


**** Salarios base - _en colombia_

| Cargo                   | Salario Mensual | Tiempo | Tiempo / Salario |
| Desarrollador Fullstack | 8_000_000       |      5 | 40_000_000       |
| Ingenieros de software  | 7_000_000       |      5 | 35_000_000       |


***** Tiempo estimado 5 meses


**** Presupuesto final

#+begin_quote
Aquì solo estamos contando con el presupuesto solo para el personal, no se tiene en cuenta el presupuesto para la arquitectura, implementaciòn del sistema, plataforma de despliegue entre otros factores importantes
#+end_quote

******* Total: COP: 75_000_000 ~ USD: 15_000

** Pautas para tener en cuenta

Lo que no se tuvo en cuenta para el ejercicio es lo siguiente:

1) Iva a la dian
2) Recurso humano: diseñador, recurso humano para tratar con los clientes, una persona de QA...
3) Retención por parte del cliente
4) Seguridad social
5) Poliza de cumplimiento

   
* Scrum - marco de trabajo

El marco de trabajo *scrum* es una herramienta que se puede adaptar a las necesidades de los desarrolladores, los cuales los adpaten para que puedan trabajar de manera más efectiva.

** De donde nace el marco de trabajo scrum

Lo que decia, el programador de la india:

- /Please, READ THE DOCS./

** Para que sirven las metodologías agíles

Darle valor a procesos en los cuales no se generan

- La mejor forma de dar aprobación al software es de que funcione
- La piramide de calidad me mide los errores, lo que es importante en está piramide es ver cuantos de lo errores reportados se ven reflejados por el cliente -> *triangulo del QA*
- Lo mas importante en este marco de trabajo siempre será *entrega de valor*.

** Pilares de scrum

1. Adaptabilidad: Estar en constante busqueda en la optimización de lo que el producto requiera en el momento
2. Inspección: Estar atentos a los cambios y pendientes del proyecto y planear siempre de forma ordenada, /no confundir con seguimiento/...
3. Transparencia: Dar claridad de la información en todo momento ya que es imprensindible para el proyecto

**** PSP - Personal Software Process

Aprender a medir su productividad, de forma periodica como tiempo se trabaja, cuanto tiempo se toma en descansos entre otros factores...

**** TSP - Team Software Process

Este irá enfocado a medir la efectividad del equipo de trabajo.


** Enfoque en el cliente

Siempre tener presente las necesidades del cliente, si se quiere tener un detalle con el al momento de cumplir los requerimientos se convierte en un valor agregado

** Sentimiento de pertenencia

Gente regular, lo que se refiere es que sea una persona comprometida y disciplinada...


* Pautas para el manifiesto agíl

Aquí se valora mucho los siguientes principios:

1) A los individuos y ss interacción por encima de los procesos y las herramientas
2) El software que funciona, por encima de la documentación exhaustiva
3) La colaboración con el cliente, por encima de la negociación contractual
4) La respuesta al cambio, por encima del seguimiento de un plan

** La colaboración con el cliente, por encima de la negociación contractual

Esto es lo mas interesante de l manifiesto ya que la relación continua con el cliente brinda formas sencillas de comunicar ideas, participando y aportando de manera efectiva lo que se necesita en el producto final, más que una contractual delimitación de responsabilidades

**** Los doce principios del manifiesto agíl

Aquí describiremos los principios en los que se fundamenta el manifiesto agíl:

1) Construcción de proyectos en torno a individuos motivados, dándoles la oportunidad y el respaldo que necesitan y procurándoles confianza para que realicen la tarea
2) El software que funciona es la principal medida de progreso
3) En intervalos regulares, el equipo reflexiona sobre la foma de ser más efectivo y ajusta su conducta en consecuencia.
4) Entregar con frecuencia software que funcione, en periodos de un par de semanas hasta un par de meses, con preferencia en los periodos breves
5) La atención continua a la excelencia técnica enaltece la agilidad
6) La forma más eficiente y efectiva de comunicar información de ida y vuelta dentro de un equipo de desarrollo es mediante la conversación cara a cara
7) La simplicidad como arte de maximizar la cantidad de trabajo que no se hace, es esencial
8) Las mejores arquitecturas, requisitos y diseños emergen de equipos que se auto organizan
9) Las personas del negocio y los desarrolladores deben trabajar juntos de forma cotidiana a traves del proyecto
10) Los procesos ágiles promueven el desarrollo sostenido. Los patrocinadores, desarrolladores y usuarios deben mantener un ritmo constante de forma indefinida
11) Nuestra principal prioridad es satisfacer al cliente a través de la entrega temprana y continua de software de valor
12) Son bienvenidos los requisitos cambiantes, incluso si llegan tarde al desarrollo. los procesos ágiles se doblegan al cambio como ventaja competitiva para el cliente
